#include "WIN32_COMPAT.H"
#include "MFC_stub.h"
#include "DLGITEM.H"
#include "RDIALOG.H"
#include "MIG.H"
#include "MIGVIEW.H"
#include "SDL.h"
#define DIRECTINPUT_VERSION 0x700 // RERUN
#include "dinput_stub.h"

#include "DOSDEFS.H"

#include "CSTRING.H" //RERUN

#include "MYANGLES.H"
#include "UNIQUEID.H"
#define F_GRAFIX
//RERUN #include "files.g"
#include "FILES.H"
#include "NODE.H"
#include "BFNUMBER.H"
