#include "WIN32_COMPAT.H"
#include "MFC_stub.h"
#include "DLGITEM.H"
#include "RDIALOG.H"
#include "MIG.H"
#include "MIGVIEW.H"
#include "SDL.h"        //RERUN
#define DIRECTINPUT_VERSION 0x700 // RERUN
#include "dinput_stub.h"
#include "CSTRING.H"
//RERUN #define STRICT

#include "DOSDEFS.H"

#define F_SOUNDS
//RERUN #include "files.g"
#include "FILES.H"
#include "WORLDINC.H"
#include "NODE.H"
#include "BFNUMBER.H"

#include <stdlib.h>


