//------------------------------------------------------------------------------
//Filename       cstring.h
//System         
//Author         Robert Slater
//Date           Wed 27 Jan 1999
//Description    
//------------------------------------------------------------------------------
#ifndef	CSTRING_Included
#define	CSTRING_Included

#if defined	(_MSC_VER)
#include "atlstr.h"
#else
#include "MigCstring.h"
#endif
#endif

