//------------------------------------------------------------------------------
//Filename       forms.h
//System         Flying Corp
//Author         Dave Whiteside
//Date           Thu 5 Oct 1995
//Description    Forms.asm replacement FORMS IS NOW PART OF THE UISheet CLASS
//				 It uses STATIC variables for various tricks
//------------------------------------------------------------------------------
